### ISSUE TITLE
Małe litery i inne znaki nie są obsługiwane

### ISSUE THREAD

**Issue by ziobron** [bogkra/crypto#2]
Co się stanie jeśli zechcę zaszyfrować taką wiadomość: "Ala ma kota, a kot ma HIV!"
Dodaj obsługę małych liter i znaków takich jak spacja, przecinek, kropka, wykrzyknik, pytajnik. Liczby możemy sobie darować ;-)

**Comment by bogkra** [comment]
- ja jestem starożytny, używam tylko majuskuły! ;) A kot może mieć co najwyżej FIV ;)
znaków specjalnych nie było w wymaganiach ;)
